"""
Interactive dashboard for Italian Parliament voting analysis.
Run: streamlit run src/dashboard.py

Requires: outputs/deputy_graph.json (generated by analysis.py)
"""

import json
from pathlib import Path

import pandas as pd
import streamlit as st
import streamlit.components.v1 as components


# ── Config ────────────────────────────────────────────────────
try:
    from config import OUTPUTS_DIR
except ImportError:
    OUTPUTS_DIR = Path("outputs")

st.set_page_config(
    page_title="Italian Parliament · Voting Network",
    page_icon="🏛️",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ── Load data ─────────────────────────────────────────────────

@st.cache_data
def load_graph():
    with open(OUTPUTS_DIR / "deputy_graph.json", "r", encoding="utf-8") as f:
        data = json.load(f)

    # Backward compatibility with older analysis output
    for node in data.get("nodes", []):
        if "voting_participation_pct" not in node:
            node["voting_participation_pct"] = node.get("attendance_pct", 0.0)

    for party in data.get("parties", []):
        if "avg_voting_participation" not in party:
            party["avg_voting_participation"] = party.get("avg_attendance", 0.0)

    return data


def save_graph_html(html_str: str, filename: str = "deputy_graph.html") -> str:
    """
    Save the generated graph HTML into the project's static folder.
    Streamlit serves ./static/* at app/static/* when static serving is enabled.
    """
    static_dir = Path("static")
    static_dir.mkdir(exist_ok=True)

    out_path = static_dir / filename
    out_path.write_text(html_str, encoding="utf-8")

    return f"static/{filename}"


data = load_graph()
nodes = data["nodes"]
edges = data["edges"]
parties = data["parties"]
meta = data["meta"]


# ── Sidebar ───────────────────────────────────────────────────

st.sidebar.markdown("## 🏛️ Filters")

all_groups = sorted(set(n["group"] for n in nodes))
selected_groups = st.sidebar.multiselect(
    "Parties",
    options=all_groups,
    default=[p["group"] for p in parties],
    help="Select which parties to display",
)

side_filter = st.sidebar.radio(
    "Side",
    ["All", "Coalition", "Opposition"],
    index=0,
)

show_edges = st.sidebar.checkbox("Show connections", value=True)
min_sim = (
    st.sidebar.slider("Min similarity for edges", 0.7, 1.0, 0.85, 0.05)
    if show_edges
    else 0.7
)

layout_mode = st.sidebar.radio(
    "Layout",
    ["UMAP (voting patterns)", "Force-directed (network)"],
    index=0,
)

st.sidebar.markdown("---")
st.sidebar.markdown(f"**{meta['n_deputies']}** deputies · **{meta['n_votes']:,}** votes")
st.sidebar.markdown(f"_{meta['date_range']}_")


# ── Filter data ───────────────────────────────────────────────

def filter_nodes(nodes, groups, side):
    filtered = [n for n in nodes if n["group"] in groups]
    if side == "Coalition":
        filtered = [n for n in filtered if n["side"] == "coalition"]
    elif side == "Opposition":
        filtered = [n for n in filtered if n["side"] == "opposition"]
    return filtered


filtered_nodes = filter_nodes(nodes, selected_groups, side_filter)
filtered_ids = {n["id"] for n in filtered_nodes}

filtered_edges = [
    e for e in edges
    if e["source"] in filtered_ids
    and e["target"] in filtered_ids
    and e["weight"] >= min_sim
] if show_edges else []


# ── D3 Network Graph ──────────────────────────────────────────

def render_d3_graph(nodes_json, edges_json, use_force):
    """Render an interactive D3.js force-directed / UMAP graph."""

    html = f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=JetBrains+Mono:wght@400;500&display=swap');

  * {{ margin: 0; padding: 0; box-sizing: border-box; }}

  html, body {{
    width: 100%;
    height: 700px;
    overflow: hidden;
    background: #0a0e17;
    font-family: 'DM Sans', sans-serif;
  }}

  #graph-wrap {{
    position: relative;
    width: 100%;
    height: 700px;
    background: #0a0e17;
    overflow: hidden;
    border-radius: 12px;
  }}

  svg {{
    width: 100%;
    height: 100%;
    display: block;
  }}

  .tooltip {{
    position: absolute;
    pointer-events: none;
    background: rgba(10, 14, 23, 0.95);
    border: 1px solid rgba(255, 255, 255, 0.15);
    border-radius: 10px;
    padding: 14px 18px;
    font-family: 'DM Sans', sans-serif;
    font-size: 13px;
    color: #c8d0e0;
    backdrop-filter: blur(12px);
    box-shadow: 0 8px 32px rgba(0,0,0,0.5);
    opacity: 0;
    transition: opacity 0.15s;
    max-width: 320px;
    z-index: 100;
  }}

  .tooltip .name {{
    font-size: 16px;
    font-weight: 700;
    color: #fff;
    margin-bottom: 4px;
  }}

  .tooltip .party {{
    font-size: 12px;
    font-weight: 500;
    margin-bottom: 10px;
    padding: 2px 8px;
    border-radius: 4px;
    display: inline-block;
  }}

  .tooltip .stats {{
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 6px 16px;
    font-family: 'JetBrains Mono', monospace;
    font-size: 12px;
  }}

  .tooltip .stat-label {{
    color: #6b7280;
    font-family: 'DM Sans', sans-serif;
  }}

  .tooltip .stat-value {{
    text-align: right;
    color: #e2e8f0;
  }}

  .legend {{
    position: absolute;
    bottom: 16px;
    left: 16px;
    background: rgba(10, 14, 23, 0.85);
    border: 1px solid rgba(255, 255, 255, 0.1);
    border-radius: 10px;
    padding: 14px 18px;
    backdrop-filter: blur(8px);
    font-size: 12px;
    color: #c8d0e0;
    max-height: 75vh;
    overflow-y: auto;
  }}

  .legend-item {{
    display: flex;
    align-items: center;
    gap: 8px;
    margin: 4px 0;
  }}

  .legend-dot {{
    width: 10px;
    height: 10px;
    border-radius: 50%;
    flex-shrink: 0;
  }}

  .legend-label {{
    white-space: nowrap;
  }}
</style>
</head>
<body>
<div id="graph-wrap">
  <div class="tooltip" id="tooltip"></div>
  <div class="legend" id="legend"></div>
  <svg id="graph"></svg>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/7.8.5/d3.min.js"></script>
<script>
const nodes = {nodes_json};
const edges = {edges_json};
const useForce = {'true' if use_force else 'false'};

const container = document.getElementById('graph-wrap');
const width = container.clientWidth || window.innerWidth;
const height = container.clientHeight || 700;

const svg = d3.select('#graph')
  .attr('width', width)
  .attr('height', height);

const g = svg.append('g');
const zoom = d3.zoom()
  .scaleExtent([0.3, 8])
  .on('zoom', (e) => g.attr('transform', e.transform));
svg.call(zoom);

const tooltip = d3.select('#tooltip');
const nodeMap = new Map(nodes.map(n => [n.id, n]));

const xExtent = d3.extent(nodes, d => d.x);
const yExtent = d3.extent(nodes, d => d.y);
const xScale = d3.scaleLinear().domain(xExtent).range([120, width - 120]);
const yScale = d3.scaleLinear().domain(yExtent).range([120, height - 120]);

nodes.forEach(n => {{
  n.sx = xScale(n.x);
  n.sy = yScale(n.y);
  if (!useForce) {{
    n.fx = n.sx;
    n.fy = n.sy;
  }}
}});

const edgeGroup = g.append('g').attr('class', 'edges');
const edgeSelection = edgeGroup.selectAll('line')
  .data(edges)
  .join('line')
  .attr('stroke', d => {{
    const s = nodeMap.get(d.source);
    const t = nodeMap.get(d.target);
    if (s && t && s.group === t.group) return s.color;
    return 'rgba(255,255,255,0.06)';
  }})
  .attr('stroke-width', d => Math.max(0.3, (d.weight - 0.7) * 3))
  .attr('stroke-opacity', d => {{
    const s = nodeMap.get(d.source);
    const t = nodeMap.get(d.target);
    if (s && t && s.group !== t.group) return 0.15;
    return 0.08;
  }});

const nodeGroup = g.append('g').attr('class', 'nodes');
const nodeSelection = nodeGroup.selectAll('circle')
  .data(nodes)
  .join('circle')
  .attr('r', d => {{
    const base = 4;
    const defBonus = Math.min(d.defection_pct * 0.5, 4);
    return base + defBonus;
  }})
  .attr('fill', d => d.color)
  .attr('stroke', d => d.side === 'coalition' ? 'rgba(255,255,255,0.3)' : 'rgba(255,255,255,0.15)')
  .attr('stroke-width', 0.5)
  .attr('cursor', 'pointer')
  .on('mouseover', function(event, d) {{
    d3.select(this)
      .transition().duration(150)
      .attr('r', parseFloat(d3.select(this).attr('r')) * 1.8)
      .attr('stroke-width', 2)
      .attr('stroke', '#fff');

    edgeSelection
      .attr('stroke-opacity', e => (e.source === d.id || e.target === d.id) ? 0.6 : 0.02)
      .attr('stroke-width', e => (e.source === d.id || e.target === d.id) ? 2 : 0.3);

    nodeSelection
      .attr('opacity', n => {{
        if (n.id === d.id) return 1;
        const connected = edges.some(e =>
          (e.source === d.id && e.target === n.id) ||
          (e.target === d.id && e.source === n.id)
        );
        return connected ? 0.9 : 0.15;
      }});

    tooltip
      .style('opacity', 1)
      .style('left', (event.pageX + 16) + 'px')
      .style('top', (event.pageY - 16) + 'px')
      .html(`
        <div class="name">${{d.id}}</div>
        <div class="party" style="background:${{d.color}}33; color:${{d.color}}">${{d.group_full}}</div>
        <div class="stats">
          <span class="stat-label">Voting participation</span>
          <span class="stat-value">${{d.voting_participation_pct.toFixed(1)}}%</span>
          <span class="stat-label">Defection</span>
          <span class="stat-value">${{d.defection_pct.toFixed(1)}}%</span>
          <span class="stat-label">Votes cast</span>
          <span class="stat-value">${{d.votes_cast.toLocaleString()}}</span>
          <span class="stat-label">Defections</span>
          <span class="stat-value">${{d.defections}}</span>
          <span class="stat-label">Side</span>
          <span class="stat-value">${{d.side}}</span>
          <span class="stat-label">Cluster</span>
          <span class="stat-value">${{d.cluster === -1 ? 'none' : d.cluster}}</span>
        </div>
      `);
  }})
  .on('mousemove', function(event) {{
    tooltip
      .style('left', (event.pageX + 16) + 'px')
      .style('top', (event.pageY - 16) + 'px');
  }})
  .on('mouseout', function(event, d) {{
    d3.select(this)
      .transition().duration(300)
      .attr('r', (() => {{
        const base = 4;
        const defBonus = Math.min(d.defection_pct * 0.5, 4);
        return base + defBonus;
      }})())
      .attr('stroke-width', 0.5)
      .attr('stroke', d.side === 'coalition' ? 'rgba(255,255,255,0.3)' : 'rgba(255,255,255,0.15)');

    edgeSelection
      .attr('stroke-opacity', e => {{
        const s = nodeMap.get(e.source);
        const t = nodeMap.get(e.target);
        if (s && t && s.group !== t.group) return 0.15;
        return 0.08;
      }})
      .attr('stroke-width', e => Math.max(0.3, (e.weight - 0.7) * 3));

    nodeSelection.attr('opacity', 1);
    tooltip.style('opacity', 0);
  }});

if (useForce) {{
  const linkData = edges.map(e => ({{
    source: nodes.find(n => n.id === e.source),
    target: nodes.find(n => n.id === e.target),
    weight: e.weight
  }})).filter(e => e.source && e.target);

  const simulation = d3.forceSimulation(nodes)
    .force('link', d3.forceLink(linkData).distance(d => (1 - d.weight) * 200).strength(d => d.weight * 0.3))
    .force('charge', d3.forceManyBody().strength(-30))
    .force('center', d3.forceCenter(width / 2, height / 2))
    .force('collision', d3.forceCollide(8))
    .on('tick', ticked);

  function ticked() {{
    edgeSelection
      .attr('x1', d => {{ const s = nodes.find(n => n.id === d.source.id || n.id === d.source); return s ? s.x : 0; }})
      .attr('y1', d => {{ const s = nodes.find(n => n.id === d.source.id || n.id === d.source); return s ? s.y : 0; }})
      .attr('x2', d => {{ const t = nodes.find(n => n.id === d.target.id || n.id === d.target); return t ? t.x : 0; }})
      .attr('y2', d => {{ const t = nodes.find(n => n.id === d.target.id || n.id === d.target); return t ? t.y : 0; }});

    nodeSelection
      .attr('cx', d => d.x)
      .attr('cy', d => d.y);
  }}
}} else {{
  edgeSelection
    .attr('x1', d => nodeMap.get(d.source)?.sx || 0)
    .attr('y1', d => nodeMap.get(d.source)?.sy || 0)
    .attr('x2', d => nodeMap.get(d.target)?.sx || 0)
    .attr('y2', d => nodeMap.get(d.target)?.sy || 0);

  nodeSelection
    .attr('cx', d => d.sx)
    .attr('cy', d => d.sy);
}}

const partyGroups = [...new Set(nodes.map(n => n.group))].sort();
const legendHTML = partyGroups.map(g => {{
  const node = nodes.find(n => n.group === g);
  const count = nodes.filter(n => n.group === g).length;
  return `<div class="legend-item">
    <div class="legend-dot" style="background:${{node?.color || '#999'}}"></div>
    <span class="legend-label">${{g}} (${{count}})</span>
  </div>`;
}}).join('');
document.getElementById('legend').innerHTML = legendHTML;

const initialTransform = d3.zoomIdentity
  .translate(width * 0.05, height * 0.05)
  .scale(0.9);
svg.call(zoom.transform, initialTransform);
</script>
</body>
</html>
"""
    return html


# ── Main layout ───────────────────────────────────────────────

st.markdown(
    """
<style>
    .block-container { padding-top: 1rem; }
    h1 { font-size: 1.8rem !important; }
    .stMetric label { font-size: 0.85rem; }
</style>
""",
    unsafe_allow_html=True,
)

st.title("🏛️ Italian Parliament · Voting Network")
st.caption(
    f"XIX Legislature · {meta['date_range']} · {meta['n_deputies']} deputies · {meta['n_votes']:,} roll-call votes"
)

with st.expander("What this dashboard shows"):
    st.markdown(
        """
This dashboard maps how deputies in the **Camera dei Deputati** voted across roll-call votes in the **XIX Legislature**.

**How to read it**
- Each **node** is a deputy.
- Each **edge** links two deputies who voted similarly.
- Node **color** shows party.
- In **UMAP** view, deputies who voted similarly appear closer together.
- In **force-directed** view, the graph emphasizes the network structure of those similarities.

**Key metrics**
- **Voting participation %** = share of roll-call votes personally cast by the deputy.
- **Defection %** = how often the deputy voted against their party's majority position.
- **Votes cast** = number of roll-call votes the deputy personally took part in.

**Important note**
“Voting participation” is **not** the same as total parliamentary presence.
A deputy may have low direct voting participation but still be officially present through **missioni** (institutional duties).
"""
    )

col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("Deputies shown", len(filtered_nodes))
col2.metric("Connections", len(filtered_edges))
col3.metric("Parties", len(selected_groups))

avg_defection = (
    sum(n["defection_pct"] for n in filtered_nodes) / len(filtered_nodes)
    if filtered_nodes else 0
)
col4.metric("Avg defection", f"{avg_defection:.1f}%")

avg_voting_participation = (
    sum(n["voting_participation_pct"] for n in filtered_nodes) / len(filtered_nodes)
    if filtered_nodes else 0
)
col5.metric("Avg voting participation", f"{avg_voting_participation:.1f}%")

use_force = layout_mode == "Force-directed (network)"
graph_html = render_d3_graph(
    json.dumps(filtered_nodes, ensure_ascii=False),
    json.dumps(filtered_edges, ensure_ascii=False),
    use_force,
)

graph_url = save_graph_html(graph_html)
st.iframe(graph_url, height=700)

st.markdown("### Party Summary")

party_data = []
for group in selected_groups:
    group_nodes = [n for n in filtered_nodes if n["group"] == group]
    if not group_nodes:
        continue
    party_data.append({
        "Party": group,
        "Deputies": len(group_nodes),
        "Side": group_nodes[0]["side"].title(),
        "Avg Voting Participation %": round(
            sum(n["voting_participation_pct"] for n in group_nodes) / len(group_nodes), 1
        ),
        "Avg Defection %": round(
            sum(n["defection_pct"] for n in group_nodes) / len(group_nodes), 2
        ),
    })

if party_data:
    st.dataframe(
        pd.DataFrame(party_data).sort_values("Deputies", ascending=False),
        width="stretch",
        hide_index=True,
    )

st.markdown("### Top Defectors")
defectors = sorted(filtered_nodes, key=lambda n: -n["defection_pct"])[:15]
defector_data = [{
    "Deputy": d["id"],
    "Party": d["group"],
    "Defection %": d["defection_pct"],
    "Defections": d["defections"],
    "Votes Cast": d["votes_cast"],
    "Voting Participation %": d["voting_participation_pct"],
} for d in defectors if d["defection_pct"] > 0]

if defector_data:
    st.dataframe(
        pd.DataFrame(defector_data),
        width="stretch",
        hide_index=True,
    )
